"""Add categorias and gastos tables

Revision ID: 624f8bd543d9
Revises: 9133fcfcd97c
Create Date: 2026-04-04 13:49:56.003631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624f8bd543d9'
down_revision = '9133fcfcd97c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
